<h2>Administrar categorias (Listado)</h2>

<table>
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        <?php if (empty($categorias)): ?>
            <tr>
                <td colspan="5">No existen categorias cargadas.</td>
            </tr>
        <?php else: ?>
            
            <?php foreach ($categorias as $categoria): ?>
                <tr>
                    <td><?php echo htmlspecialchars($categoria['nombre']); ?></td>
                    <td>
                        <a href="admin/eliminar_categoria/<?php echo $categoria['id']; ?>" class="btn-eliminar">Eliminar</a>
                        
                        <a href="admin/editar_categoria/<?php echo $categoria['id']; ?>" class="btn-editar">Editar</a>
                    </td>
                </tr>
            <?php endforeach; ?>
           
        <?php endif; ?>
         <a href="admin/agregar_categoria/" class="btn-agregar">agregar</a>
    </tbody>
</table>