<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Usamos BASE_URL para asegurar que el CSS cargue correctamente -->
    <link rel="stylesheet" href="<?= BASE_URL ?>/public/css/style.css">
    
    <title>NutriPoint - Dietética Saludable</title>
</head>
<body>
    <header>
        <div>
            <h1>NUTRIPOINT</h1>
        </div>  

        <div>
            <!-- Menú de navegación principal -->
            <ul> 
                <li><a href="<?= BASE_URL ?>/productos">Productos</a></li>
                <!-- Este li se llenará dinámicamente con las categorías -->
                <?php
                    // show categorias en li que genere de maneta dinamica todas la categorias en lista 
                ?>
            </ul>
        </div>
        <div>
            <!-- Enlaces de login/registro. El login lleva a la ruta de administración -->
            <a href="<?= BASE_URL ?>/admin/login"><p>Iniciar Sesión</p></a>
            <p>Registro</p> 
        </div>
    </header>
    
    <!-- Aquí abre la etiqueta <main>. -->
    <main>